import pandas as pd
oder=pd.read_excel("C:\\Users\\DELL\\Downloads\\sales_returns.xlsx",sheet_name="Orders")
print(oder.head())
print(oder.shape)
returns=pd.read_excel("C:\\Users\\DELL\\Downloads\\sales_returns.xlsx",sheet_name="Returns")
print(returns.head())
print(returns.shape)
merg=oder.merge(returns,on="Order ID")
print(merg.head())
print(merg.shape)
print()
mer=oder.merge(returns,on="Order ID",how="left")
print(mer.head())
print(mer.shape)
print()
print(mer[mer["Returned"]=="Yes"].head())
print()
mer["Returned"]=mer["Returned"].astype("str")
print(mer)
print(merg["Returned"].astype("str"))
